name: Reusable workflow example

on:
  workflow_call:
    inputs:
      repo:
        required: true
        type: string
      issue:
        required: true
        type: number
    secrets:
      token:
        required: true

jobs:
  Prettier:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v4
      with:
        repository: '${{ inputs.repo }}'
        ref: master
        token: ${{ secrets.token }}

    - name: Git login
      run: echo ${{ secrets.token }} | gh auth login --with-token

    - name: Checkout Pull Request
      run: gh pr checkout ${{ inputs.issue }}
  
    - name: Install prettier
      run: npm install --save-dev --save-exact prettier
      
    - name: Add files to ignore
      run: echo '*.yml' > .prettierignore

    - name: Prettier formatting
      run: npx prettier . --write

    - name: Check git status
      run: git status
    

    - name: Commit formatted files
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Prettier formatting
      env:
        GITHUB_TOKEN: ${{ secrets.token }}

    
